site_name: Physicos Academia

site_description: Treinos, dicas e informações para a sua evolução física.
site_author: Physicos Academia

nav:
  - Início: index.md
  - Treinos (Planilhas):
      - Treino Masculino (Opção 1): planilhas/treino-masculino.md
  - Exercícios:
      - Peito:
          - Supino Reto: exercicios/peito/supino-reto.md
          - Supino Inclinado: exercicios/peito/supino-inclinado.md
          - Supino Declinado: exercicios/peito/supino-declinado.md

theme:
  name: readthedocs
  language: pt-BR

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables

copyright: Todos os direitos reservados. &copy; 2025 Physicos Academia
